///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

#if ENABLE_INPUT_SYSTEM

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [DisplayName("InputSystem_IsFirstLayoutBasedOnSecond")]
    [Category("UnityEngine/InputSystem")]
    [AddComponentMenu("IsFirstLayoutBasedOnSecond(String, String)")]
    public sealed class InputSystem_IsFirstLayoutBasedOnSecond_String_String_Method_Decorator : ConditionDecorator
    {
        [Space]
        public Megumin.Binding.RefVar_String firstLayoutName;
        public Megumin.Binding.RefVar_String secondLayoutName;

        [Space]
        public Megumin.Binding.RefVar_Bool SaveValueTo;

        public override bool CheckCondition(object options = null)
        {
            var result = UnityEngine.InputSystem.InputSystem.IsFirstLayoutBasedOnSecond(firstLayoutName, secondLayoutName);

            if (SaveValueTo != null)
            {
                SaveValueTo.Value = result;
            }

            return result;
        }

    }
}

#endif




