///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

#if ENABLE_INPUT_SYSTEM

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [DisplayName("InputSystem_GetNameOfBaseLayout")]
    [Category("UnityEngine/InputSystem")]
    [AddComponentMenu("GetNameOfBaseLayout(String)")]
    public sealed class InputSystem_GetNameOfBaseLayout_String_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_String layoutName;

        [Space]
        public Megumin.Binding.RefVar_String SaveValueTo;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = UnityEngine.InputSystem.InputSystem.GetNameOfBaseLayout(layoutName);

            if (SaveValueTo != null)
            {
                SaveValueTo.Value = result;
            }

            return Status.Succeeded;
        }
    }
}

#endif




