///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

#if ENABLE_INPUT_SYSTEM

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [DisplayName("InputSystem_RegisterLayoutMatcher")]
    [Category("UnityEngine/InputSystem")]
    [AddComponentMenu("RegisterLayoutMatcher(String, InputDeviceMatcher)")]
    public sealed class InputSystem_RegisterLayoutMatcher_String_InputDeviceMatcher_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_String layoutName;
        public Megumin.Binding.RefVar<UnityEngine.InputSystem.Layouts.InputDeviceMatcher> matcher;

        protected override Status OnTick(BTNode from, object options = null)
        {
            UnityEngine.InputSystem.InputSystem.RegisterLayoutMatcher(layoutName, matcher);
            return Status.Succeeded;
        }
    }
}

#endif




