///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

#if ENABLE_INPUT_SYSTEM

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [DisplayName("InputSystem_RegisterLayout")]
    [Category("UnityEngine/InputSystem")]
    [AddComponentMenu("RegisterLayout(String, String, Nullable`1)")]
    public sealed class InputSystem_RegisterLayout_String_String_Nullable_1_InputDeviceMatcher_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_String json;
        public Megumin.Binding.RefVar_String name;
        public Megumin.Binding.RefVar<System.Nullable<UnityEngine.InputSystem.Layouts.InputDeviceMatcher>> matches;

        protected override Status OnTick(BTNode from, object options = null)
        {
            UnityEngine.InputSystem.InputSystem.RegisterLayout(json, name, matches);
            return Status.Succeeded;
        }
    }
}

#endif




