///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

#if ENABLE_INPUT_SYSTEM

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("d_DefaultAsset Icon")]
    [DisplayName("InputActionAsset_ToJson")]
    [Category("UnityEngine/InputActionAsset")]
    [AddComponentMenu("ToJson")]
    public sealed class InputActionAsset_ToJson_Method_Decorator : CompareDecorator<string>
    {
        [Space]
        public UnityEngine.InputSystem.InputActionAsset MyAgent;

        [Space]
        public Megumin.Binding.RefVar_String CompareTo;

        [Space]
        public Megumin.Binding.RefVar_String SaveValueTo;

        public override string GetResult()
        {
            var result = ((UnityEngine.InputSystem.InputActionAsset)MyAgent).ToJson();

            if (SaveValueTo != null)
            {
                SaveValueTo.Value = result;
            }

            return result;
        }

        public override string GetCompareTo()
        {
            return CompareTo;
        }

    }
}

#endif




