///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("d_AudioSource Icon")]
    [DisplayName("AudioSource_SetCustomCurve")]
    [Category("UnityEngine/AudioSource")]
    [AddComponentMenu("SetCustomCurve(AudioSourceCurveType, AnimationCurve)")]
    public sealed class AudioSource_SetCustomCurve_AudioSourceCurveType_AnimationCurve_Node : BTActionNode<UnityEngine.AudioSource>
    {
        [Space]
        public Megumin.Binding.RefVar<UnityEngine.AudioSourceCurveType> type;
        public Megumin.Binding.RefVar_AnimationCurve curve;

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.AudioSource)MyAgent).SetCustomCurve(type, curve);
            return Status.Succeeded;
        }
    }
}




