///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("d_AudioSource Icon")]
    [DisplayName("AudioSource_GetSpectrumData")]
    [Category("UnityEngine/AudioSource")]
    [AddComponentMenu("GetSpectrumData(Single[], Int32, FFTWindow)")]
    public sealed class AudioSource_GetSpectrumData_SingleArray_Int32_FFTWindow_Node : BTActionNode<UnityEngine.AudioSource>
    {
        [Space]
        public Megumin.Binding.RefVar_Float_Array samples;
        public Megumin.Binding.RefVar_Int channel;
        public Megumin.Binding.RefVar<UnityEngine.FFTWindow> window;

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.AudioSource)MyAgent).GetSpectrumData(samples, channel, window);
            return Status.Succeeded;
        }
    }
}




