///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [DisplayName("Quaternion_Normalize")]
    [Category("UnityEngine/Quaternion")]
    [AddComponentMenu("Normalize")]
    public sealed class Quaternion_Normalize_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar<UnityEngine.Quaternion> MyAgent;

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.Quaternion)MyAgent).Normalize();
            return Status.Succeeded;
        }
    }
}




