///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [DisplayName("SceneManager_LoadScene")]
    [Category("UnityEngine/SceneManager")]
    [AddComponentMenu("LoadScene(Int32, LoadSceneParameters)")]
    public sealed class SceneManager_LoadScene_Int32_LoadSceneParameters_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_Int sceneBuildIndex;
        public Megumin.Binding.RefVar<UnityEngine.SceneManagement.LoadSceneParameters> parameters;

        [Space]
        public Megumin.Binding.RefVar<UnityEngine.SceneManagement.Scene> SaveValueTo;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = UnityEngine.SceneManagement.SceneManager.LoadScene(sceneBuildIndex, parameters);

            if (SaveValueTo != null)
            {
                SaveValueTo.Value = result;
            }

            return Status.Succeeded;
        }
    }
}




