///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [DisplayName("SceneManager_LoadScene")]
    [Category("UnityEngine/SceneManager")]
    [AddComponentMenu("LoadScene(Int32, LoadSceneMode)")]
    public sealed class SceneManager_LoadScene_Int32_LoadSceneMode_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_Int sceneBuildIndex;
        public Megumin.Binding.RefVar<UnityEngine.SceneManagement.LoadSceneMode> mode;

        protected override Status OnTick(BTNode from, object options = null)
        {
            UnityEngine.SceneManagement.SceneManager.LoadScene(sceneBuildIndex, mode);
            return Status.Succeeded;
        }
    }
}




