///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [DisplayName("SceneManager_MoveGameObjectToScene")]
    [Category("UnityEngine/SceneManager")]
    [AddComponentMenu("MoveGameObjectToScene(GameObject, Scene)")]
    public sealed class SceneManager_MoveGameObjectToScene_GameObject_Scene_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_GameObject go;
        public Megumin.Binding.RefVar<UnityEngine.SceneManagement.Scene> scene;

        protected override Status OnTick(BTNode from, object options = null)
        {
            UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(go, scene);
            return Status.Succeeded;
        }
    }
}




