///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("d_Animator Icon")]
    [DisplayName("Animator_SetIKHintPosition")]
    [Category("UnityEngine/Animator")]
    [AddComponentMenu("SetIKHintPosition(AvatarIKHint, Vector3)")]
    public sealed class Animator_SetIKHintPosition_AvatarIKHint_Vector3_Node : BTActionNode<UnityEngine.Animator>
    {
        [Space]
        public Megumin.Binding.RefVar<UnityEngine.AvatarIKHint> hint;
        public Megumin.Binding.RefVar_Vector3 hintPosition;

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.Animator)MyAgent).SetIKHintPosition(hint, hintPosition);
            return Status.Succeeded;
        }
    }
}




