///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：Megumin.GameFramework.AI.BehaviorTree.Editor.NodeGenerator
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("d_GameObject Icon")]
    [DisplayName("GameObject_BroadcastMessage")]
    [Category("UnityEngine/GameObject")]
    [AddComponentMenu("BroadcastMessage(String, SendMessageOptions)")]
    public sealed class GameObject_BroadcastMessage_String_SendMessageOptions_Node : BTActionNode<UnityEngine.GameObject>
    {
        [Space]
        public Megumin.Binding.RefVar_String methodName;
        public Megumin.Binding.RefVar<UnityEngine.SendMessageOptions> options;

        protected override Status OnTick(BTNode from, object options1 = null)
        {
            ((UnityEngine.GameObject)MyAgent).BroadcastMessage(methodName, options);
            return Status.Succeeded;
        }
    }
}




